// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebihgvbkxwikuqehinur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViaWhndmJreHdpa3VxZWhpbnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjYwNTUsImV4cCI6MjA2NzEwMjA1NX0.BKEFoE9DTLEBUE350HwWcN0rfjz8fY4NeadaL8S2H6M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});